Repository hs-study-group/algorithm, pull requests merged in 2022-08, with the labels that each got.

#79 [BOJ] 알고스팟 / Gold4
  BOJ/Dijkstra/1261/Blanc_et_Noir/Main.java
Labels: Gold IV

#80 [PGS] 올바른 괄호 / level2
  PGS/Stack/올바른-괄호/Blanc_et_Noir/Solution.java
Labels: Level 2

#81 [PGS] [Vector] [최소직사각형]
  PGS/Vector/최소직사각형/inseonyun/main.cpp
Labels: Level 1

#82 [PGS] [3차] 압축 / Level2
  PGS/String/[3차]-압축/Blanc_et_Noir/Solution.java
Labels: Level 2

#83 [PGS] [Stack] [수식 최대화]
  PGS/Stack/수식-최대화/Blanc_et_Noir/Solution.java
Labels: Level 2

#84 [PGS] [String] [성격 유형 검사하기]
  PGS/String/성격-유형-검사하기/inseonyun/main.cpp
Labels: Level 1

#85 [PGS] [String] [성격 유형 검사하기]
  PGS/String/성격-유형-검사하기/Blanc_et_Noir/Solution.java
Labels: Level 1

#86 [PGS] [Vector] [최소직사각형]
  PGS/Vector/최소직사각형/Blanc_et_Noir/Solution.java
Labels: Level 1

#87 [PGS] [Sort] [최솟값 만들기]
  PGS/Sort/최솟값-만들기/Blanc_et_Noir/Solution.java
Labels: Level 2

#88 [PGS] [Dijkstra] [배달]
  PGS/Dijkstra/배달/Blanc_et_Noir/Solution.java
Labels: Level 2

#89 [PGS] [Queue] [두 큐 합 같게 만들기]
  PGS/Queue/두-큐-합-같게-만들기/Blanc_et_Noir/Solution.java
Labels: Level 2

#90 [PGS] [Queue] [다리를 지나는 트럭]
  PGS/Queue/다리를-지나는-트럭/Blanc_et_Noir/Solution.java
Labels: Level 2

#91 [BOJ] [BFS] [2468] [안전 영역]
  BOJ/BFS/2468/Blanc_et_Noir/Main.java
Labels: Siver I

#92 [BOJ] [SegmentTree] [1275] [커피숍2]
  BOJ/SegmentTree/1275/Blanc_et_Noir/Main.java
Labels: Gold I

#93 [BOJ] [SegmentTree] [13544] [수열과 쿼리 3]
  BOJ/SegmentTree/13544/Blanc_et_Noir/Main.java
Labels: Platinum III

#94 [PGS] [DFS] [피로도]
  PGS/DFS/피로도/Blanc_et_Noir/Solution.java
Labels: Level 2

#95 [PGS] [BFS] [코딩 테스트 공부]
  PGS/BFS/코딩-테스트-공부/Blanc_et_Noir/Solution.java
Labels: Level 3

#96 [PGS] [Stack] [괄호 회전하기]
  PGS/Stack/괄호-회전하기/Blanc_et_Noir/Solution.java
Labels: Level 2

#97 [PGS] [Hash] [영어 끝말잇기]
  PGS/Hash/영어-끝말잇기/Blanc_et_Noir/Solution.java
Labels: Level 2
