Repository hs-study-group/algorithm, pull requests merged in 2022-05, with the labels that each got.

#1 [PGS] [ETC] [숫자 문자열과 영단어]
  PGS/ETC/숫자-문자열과-영단어/inseonyun/main.cpp
Labels: Level 1

#3 [PGS] [ETC] [주차 요금 계산]
  PGS/ETC/주차-요금-계산/inseonyun/main.cpp
Labels: Level 2

#5 [BOJ] 설탕 배달 / Bronze1
  BOJ/DP/2839/calisyj/sugar.py
Labels: Bronze I

#6 [PGS] [BitMasking] [비밀지도]
  .project
  PGS/BitMasking/비밀지도/Blanc_et_Noir/Solution.java
Labels: Level 1

#7 [PGS] 문자열 압축 / level2
  PGS/String/문자열-압축/Blanc_et_Noir/Solution.java
Labels: Level 2

#8 [PGS] 프렌즈4블록 / level2
  PGS/ETC/프렌즈4블록/Blanc_et_Noir/Solution.java
Labels: Level 2

#9 [PGS] [ETC] [주차 요금 계산]
  PGS/ETC/주차-요금-계산/Blanc_et_Noir/Solution.java
Labels: Level 2

#10 [PGS] [ETC] [크레인 인형뽑기 게임]
  PGS/ETC/크레인-인형뽑기-게임/Blanc_et_Noir/Solution.java
Labels: Level 1

#11 [PGS] [ETC] [캐시]
  PGS/ETC/캐시/Blanc_et_Noir/Solution.java
Labels: Level 2

#12 [BOJ] [DP] [12738] [가장 긴 증가하는 부분 수열 3]
  BOJ/DP/12738/Blanc_et_Noir/Main.java
Labels: Gold II

#13 [PGS] 오픈채팅방 / level2
  PGS/ETC/오픈채팅방/Blanc_et_Noir/Solution.java
Labels: Level 2

#14 [PGS] [BFS] [카카오프렌즈 컬러링북]
  PGS/BFS/카카오프렌즈-컬러링북/Blanc_et_Noir/Solution.java
Labels: Level 2

#15 [PGS] [ETC] [단체사진 찍기]
  PGS/ETC/단체사진-찍기/Blanc_et_Noir/Solution.java
Labels: Level 2

#16 [PGS] [ETC] [실패율]
  PGS/ETC/실패율/inseonyun/main.cpp
Labels: Level 1

#17 [PGS] [String] [메뉴 리뉴얼]
  PGS/String/메뉴-리뉴얼/Blanc_et_Noir/Solution.java
Labels: Level 2

#18 [PGS] [ETC] [후보키]
  PGS/ETC/후보키/Blanc_et_Noir/Solution.java
Labels: Level 2

#19 [PGS] [ETC] [다트게임]
  PGS/ETC/다트게임/inseonyun/main.cpp
Labels: Level 1

#21 [PGS] [Array] [스킬 체크 레벨1] [행렬의 덧셈]
  PGS/Array/스킬 체크 레벨1/calisyj/행렬의 덧셈.py
Labels: Level 1

#22 [PGS] K번째수 / Level1
  PGS/Sort/K번째수/calisyj/k번째수.py
Labels: Level 1

#23 [BOJ] [DFS] [24479] [알고리즘 수업 - 깊이 우선 탐색 1]
  BOJ/DFS/24479/inseonyun/main.cpp
Labels: Silver II

#24 [PGS] [Sort] [K번째수]
  PGS/Sort/K번째수/Blanc_et_Noir/Solution.java
Labels: Level 1

#25 [BOJ] [SegmentTree] [10868] [최솟값]
  BOJ/SegmentTree/10868/Blanc_et_Noir/Main.java
Labels: Gold I

#27 [BOJ] [SegmentTree] [2042] [구간 합 구하기]
  BOJ/SegmentTree/2042/Blanc_et_Noir/Main.java
Labels: Gold I

#28 [BOJ] [SegmentTree] [2268] [수들의 합 7]
  BOJ/SegmentTree/2268/Blanc_et_Noir/Main.java
Labels: Gold I

#29 [BOJ] [DFS] [24480] [알고리즘 수업 - 깊이 우선 탐색 2]
  BOJ/DFS/24480/inseonyun/main.cpp
Labels: Silver II

#30 [BOJ] [BFS] [24444] [알고리즘 수업 - 너비 우선 탐색 1]
  BOJ/BFS/24444/inseonyun/main.cpp
Labels: Silver II

#31 [PGS] 두 개 뽑아서 더하기 / Level1
  PGS/Sort/두 개 뽑아서 더하기/calisyj/두 개 뽑아서 더하기.py
Labels: Level 1

#32 [BOJ] [BFS] [24445] [알고리즘 수업 - 너비 우선 탐색 2]
  BOJ/BFS/24445/inseonyun/main.cpp
Labels: Silver II

#33 [BOJ] [BFS] [16928] [뱀과 사다리 게임]
  BOJ/BFS/16928/inseonyun/main.cpp
Labels: Gold V

#34 [BOJ] [SegementTree] [18436] [수열과 쿼리 37]
  BOJ/SegmentTree/18436/Blanc_et_Noir/Main.java
Labels: Gold I

#35 [PGS] 신고 결과 받기 / Level1
  PGS/ETC/신고-결과-받기/calisyj/신고결과받기.py
Labels: Level 1

#36 [PGS] [Hash] [] [완주하지 못한 선수]
  PGS/Hash/완주하지 못한 선수/calisyj/완주하지 못한 선수.py
Labels: Level 1
