Repository hs-study-group/algorithm, pull requests merged in 2022-11, with the labels that each got.

#223 [PGS] [String] [가장 긴 팰린드롬]
  PGS/String/가장-긴-팰린드롬/Blanc_et_Noir/Solution.java
Labels: Level 3

#224 [PGS] [BFS] [지역 이동]
  PGS/BFS/지형-이동/Blanc_et_Noir/Solution.java
Labels: Level 3

#225 [BOJ] [SegementTree] [11962] [Counting Haybales]
  BOJ/SegmentTree/11962/Blanc_et_Noir/Main.java
Labels: Platinum IV

#227 [BOJ] [BFS] [18500] [미네랄 2]
  BOJ/BFS/18500/Blanc_et_Noir/Main.java
Labels: Gold I

#228 [BOJ] [Spanning-Tree] [10021] [Watering the Fields]
  BOJ/Spanning-Tree/10021/Blanc_et_Noir/Main.java
Labels: Gold III

#229 [SWEA] [DFS] [15612] [체스판 위의 룩 배치]
  SWEA/D3/15612/inseonyun/SWEA_15612.cpp
Labels: D3

#230 [SWEA] [String] [15758] [무한 문자열]
  SWEA/D3/15758/inseonyun/SWEA_15758.cpp
Labels: D3

#231 [PGS] [DP] [연속 부분 수열 합의 개수]
  PGS/DP/연속-부분-수열-합의-개수/Blanc_et_Noir/Solution.java
Labels: Level 2

#232 [PGS] [DP] [땅따먹기]
  PGS/DP/땅따먹기/Blanc_et_Noir/Solution.java
Labels: Level 2

#233 [SWEA] [ETC] [14178] [1차원 정원]
  SWEA/D3/14178/inseonyun/SWEA_14178.cpp
Labels: D3

#235 [PGS] [Deque] [구명보트]
  PGS/Deque/구명보트/Blanc_et_Noir/Solution.java
Labels: Level 2

#236 [BOJ] [DP] [12920] [평범한 배낭 2]
  BOJ/DP/12920/Blanc_et_Noir/Main.java
Labels: Platinum IV

#237 [BOJ] [SegmentTree] [1989] [부분배열 고르기 2]
  BOJ/SegmentTree/1989/Blanc_et_Noir/Main.java
Labels: Platinum V

#239 [BOJ] [SegmentTree] [2104] [부분배열 고르기]
  BOJ/SegmentTree/2104/Blanc_et_Noir/Main.java
Labels: Platinum V

#240 [PGS] [Sort] [귤 고르기]
  PGS/Sort/귤-고르기/inseonyun/PGS_Select_Tangerine.cpp
Labels: Level 2

#241 [PGS] [ETC] [숫자 카드 나누기]
  PGS/ETC/숫자-카드-나누기/inseonyun/PGS_DivideNumberCard.cpp
Labels: Level 2

#242 [PGS] [Sort] [귤 고르기]
  PGS/Sort/귤-고르기/Blanc_et_Noir/Solution.java
Labels: Level 2
