Repository hs-study-group/algorithm, pull requests merged in 2022-10, with the labels that each got.

#138 [BOJ] [Topological-Sort] [2623] [음악프로그램]
  BOJ/Topological-Sort/2623/Blanc_et_Noir/Main.java
Labels: Gold III

#139 [BOJ] [Spanning-Tree] [1197] [최소 스패닝 트리]
  BOJ/Spanning-Tree/1197/Blanc_et-Noir/Main.java
Labels: Gold IV

#140 [BOJ] [Spanning-Tree] [1647] [도시 분할 계획]
  BOJ/Spanning-Tree/1647/Blanc_et_Noir/Main.java
Labels: Gold IV

#141 [BOJ] [Disjoint-Set] [20040] [사이클 게임]
  BOJ/Disjoint-Set/22040/Blanc_et_Noir/Main.java
Labels: Gold IV

#142 [BOJ] [Spanning-Tree] [4386] [별자리 만들기]
  BOJ/Spanning-Tree/4386/Blanc_et_Noir/Main.java
Labels: Gold IV

#143 [BOJ] [Floyd-Warshall] [11404] [플로이드]
  BOJ/Floyd-warshall/11404/Blanc_et_Noir/Main.java
Labels: Gold IV

#144 [PGS] [BackTracking] [여행경로]
  PGS/BackTracking/여행경로/Blanc_et_Noir/Solution.java
Labels: Gold III

#145 [PGS] [TopologicalSort] [스킬트리]
  PGS/TopologicalSort/스킬트리/Blanc_et_Noir/Solution.java
Labels: Level 2

#146 [BOJ] [BFS] [20419] [화살표 미로 (Easy)]
  BOJ/BFS/20419/Blanc_et_Noir/Main.java
Labels: Gold III

#147 [PGS] [ETC] [다음 큰 숫자]
  PGS/ETC/다음-큰-숫자/Blanc_et_Noir/Solution.cpp
Labels: Level 2

#148 [BOJ] [Back-Tracking] [2239] [스도쿠]
  BOJ/Back-Tracking/2239/Blanc_et_Noir/Main.java
Labels: Gold IV

#149 [BOJ] [BFS] [20420] [화살표 미로 (Normal)]
  BOJ/BFS/20420/Blanc_et_Noir/Main.java
Labels: Gold II

#150 [BOJ] [Bit-Masking] [2464] [비밀번호]
  BOJ/Bit-Masking/2464/Blanc_et_Noir/Main.java
Labels: Gold II

#151 [BOJ] [BFS] [6087] [레이저 통신]
  BOJ/BFS/6087/Blanc_et_Noir/Main.java
Labels: Gold III

#152 [BOJ] [Bit-Masking] [2064] [IP 주소]
  BOJ/Bit-Masking/2064/Blanc_et_Noir/Main.java
Labels: Gold III

#153 [BOJ] [Floyd-Warshall] [1956] [운동]
  BOJ/Floyd-warshall/1956/Blanc_et_Noir/Main.java
Labels: Gold IV

#154 P digit
  BOJ/Bruteforce/9663/Blanc_et_Noir/15686/15868.py
Labels: Gold V

#155 [BOJ] 가장 큰 정사각형 / Gold 4
  BOJ/DP/1915/P-digit/1915.py
Labels: Gold IV

#158 [BOJ] [brute force] [15868] [치킨 배달]
  BOJ/Bruteforce/15686/P-digit/main.py
Labels: Gold V

#161 [BOJ] [Two-Pointer] [1806] [부분합]
  BOJ/Two-Pointer/1806/Blanc_et_Noir/Main.java
Labels: Gold IV

#162 [BOJ] [Greedy] [13904] [과제]
  BOJ/Greedy/13904/Blanc_et_Noir/Main.java
Labels: Gold III

#163 [BOJ] [BFS] [13459] [구슬탈출]
  BOJ/BFS/13459/Blanc_et_Noir/Main.java
Labels: Gold II

#164 [BOJ] [BFS] [13460] [구슬 탈출 2]
  BOJ/BFS/13460/Blanc_et_Noir/Main.java
Labels: Gold I

#166 [BOJ] [BFS] [14502] [연구소]
  BOJ/BFS/14502/Blanc_et_Noir/Main.java
Labels: Gold IV

#167 [BOJ] [BFS] [14502] [연구소]
  BOJ/BFS/14502/inseonyun/main.cpp
Labels: Gold IV

#168 [BOJ] [BFS] [15644] [구슬 탈출 3]
  BOJ/BFS/15644/Blanc_et_Noir/Main.java
Labels: Gold I

#169 [BOJ] [BFS] [15653] [구슬 탈출 4]
  BOJ/BFS/15653/Blanc_et_Noir/Main.java
Labels: Gold I

#170 [BOJ] [BFS] [11725] [트리의 부모 찾기]
  BOJ/BFS/11725/inseonyun/main.cpp
Labels: Silver II

#171 [BOJ] [BFS] [2583] [영역 구하기]
  BOJ/BFS/2583/inseonyun/main.cpp
Labels: Silver I

#172 [BOJ] [BFS] [16441] [아기돼지와 늑대]
  BOJ/BFS/16441/Blanc_et_Noir/Main.java
Labels: Gold III

#173 [BOJ] [BFS] [4963] [섬의 개수]
  BOJ/BFS/4963/inseonyun/main.cpp
Labels: Silver II

#174 [BOJ] [Brute force] [1107] [리모컨]
  BOJ/Bruteforce/1107/main.py
Labels: Gold V

#177 [BOJ] [BFS] [4485] [녹색 옷 입은 애가 젤다지?]
  BOJ/BFS/4485/Blanc_et_Noir/Main.java
Labels: Gold IV

#178 [BOJ] [DAC] [1074] [Z]
  BOJ/DAC/1074/P-digit/main.py
Labels: Silver I

#179 [PGS] [ETC] [다단계 칫솔 판매]
  PGS/ETC/다단계-칫솔-판매/Blanc_et_Noir/Solution.java
Labels: Level 3

#180 [BOJ] [BFS] [10026] [적록색약]
  BOJ/BFS/10026/inseonyun/main.cpp
Labels: Gold V

#181 [PGS] [DP] [멀리 뛰기]
  PGS/DP/멀리-뛰기/Blanc_et_Noir/Solution.java
Labels: Level 2

#182 [PGS] [DP] [피보나치 수]
  PGS/DP/피보나치-수/Blanc_et_Noir/Solution.java
Labels: Level 2

#183 [BOJ] [DFS] [1260] [DFS와 BFS]
  BOJ/DFS/1260/main.py
Labels: Silver II

#186 [BOJ] [BFS] [16236] [아기상어]
  BOJ/BFS/16236/inseonyun/main.cpp
Labels: Gold III

#187 [PGS] [ETC] [점프와 순간 이동]
  PGS/ETC/점프와-순간-이동/Blanc_et_Noir/Main.java
Labels: Level 2

#188 [BOJ] [BFS] [13459] [구슬 탈출]
  BOJ/BFS/13459/inseonyun/main.cpp
Labels: Gold II

#189 [PGS] [String] [[1차] 뉴스 클러스터링]
  PGS/String/[1차]-뉴스-클러스터링/Blanc_et_Noir/Solution.java
Labels: Level 2

#190 [PGS] [Stack] [택배상자]
  PGS/Stack/택배상자/Blanc_et_Noir/Solution.java
Labels: Level 2

#191 [PGS] [ETC] [최고의 집합]
  PGS/ETC/최고의-집합/Blanc_et_Noir/Solution.java
Labels: Level 3

#192 [BOJ] [BFS] [13460] [구슬 탈출2]
  BOJ/BFS/13460/inseonyun/main.cpp
Labels: Gold I

#193 [PGS] [DP] [등굣길]
  PGS/DP/등굣길/Blanc_et_Noir/Solution.java
Labels: Level 3

#194 [BOJ] [BFS] [1389] [케빈 베이컨의 6단계 법칙]
  BOJ/BFS/1389/inseonyun/main.cpp
Labels: Silver I

#197 [BOJ] [SegmentTree] [15967] [에바쿰]
  BOJ/SegmentTree/15967/Blanc_et_Noir/Main.java
Labels: Platinum IV

#198 [BOJ] [BFS] [3055] [탈출]
  BOJ/BFS/3055/Blanc_et_Noir/Main.java
Labels: Gold IV

#199 [BOJ] [BFS] [16234] [인구 이동]
  BOJ/BFS/16234/inseonyun/main.cpp
Labels: Gold V

#200 [BOJ] [BFS] [3055] [탈출]
  BOJ/BFS/3055/inseonyun/main.cpp
Labels: Gold IV

#202 [PGS] [DFS] [혼자 놀기의 달인]
  PGS/DFS/혼자-놀기의-달인/Blanc_et_Noir/Solution.java
Labels: Level 2

#203 [PGS] [Dijkstra] [부대복귀]
  PGS/Dijkstra/부대복귀/Blanc_et_Noir/Solution.java
Labels: Level 3

#204 [BOJ] [DFS] [1987] [알파벳]
  BOJ/DFS/1987/inseonyun/main.cpp
Labels: Gold IV

#205 [PGS] [BFS] [카운트 다운]
  PGS/BFS/카운트-다운/Blanc_et_Noir/Solution.java
Labels: Level 3

#206 [BOJ] [DFS] [1520] [내리막 길]
  BOJ/DFS/1520/inseonyun/main.cpp
Labels: Gold III

#208 [PGS] [BackTracking] [양궁대회]
  PGS/BackTracking/양궁대회/Blanc_et_Noir/Solution.java
Labels: Level 2

#209 [SWEA] [ETC] [15230] [알파벳 공부]
  SWEA/D3/15230/inseonyun/SWEA_15230.cpp
Labels: D3

#210 [SWEA] [DFS, BFS] [14413] [격자판 칠하기]
  SWEA/D3/14413/inseonyun/SWEA_14413.cpp
Labels: D3

#211 [BOJ] [SegmentTree] [1725] [히스토그램]
  BOJ/SegmentTree/1725/Blanc_et_Noir/Main.java
Labels: Platinum V

#213 [SWEA] [ETC] [13732] [정사각형 판정]
  SWEA/D3/13732/inseonyun/SWEA_13732.cpp
Labels: D3

#214 [BOJ] [SegmentTree] [6549] [히스토그램에서 가장 큰 직사각형]
  BOJ/SegmentTree/6549/Blanc_et_Noir/Main.java
Labels: Platinum V

#215 [SWEA] [ETC] [14692] [통나무 자르기]
  SWEA/D3/14692/inseonyun/SWEA_14692.cpp
Labels: D3

#216 [BOJ] [SegmentTree] [14438] [수열과 쿼리 17]
  BOJ/SegmentTree/14438/Blanc_et_Noir/Main.java
Labels: Gold I

#217 [PGS] [DFS] [모두 0으로 만들기]
  PGS/DFS/모두-0으로-만들기/Blanc_et_Noir/Solution.java
Labels: Level 3

#218 [SWEA] [ETC] [14557] [카드 제거]
  SWEA/D4/14557/inseonyun/SWEA_14557.cpp
Labels: D4

#219 [BOJ] [SegmentTree] [2835] [인기도 조사]
  BOJ/SegmentTree/2835/Blanc_et_Noir/Main.cpp
Labels: Platinum IV

#220 [PGS] [Stack] [햄버거 만들기]
  PGS/Stack/햄버거-만들기/Blanc_et_Noir/Solution.java
Labels: Level 1

#221 [PGS] [TwoPointer] [보석 쇼핑]
  PGS/TwoPointer/보석-쇼핑/Blanc_et_Noir/Solution.java
Labels: Level 3
